[package]
name = "EasyMDNades"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
regex = "1.11.1"
reqwest = {version="0.12.22", features=["blocking", "json"]}
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.142"
tokio = "1.47.1"

